Task 1:
    name: Write detailed requirements and specifications
    agent: Product Manager
    description: |
        Based on the project description below, write detailed technical specification for the project.
        The specification should include:
        - A document title and a clear description of the project
        - The key features and functionalities required
        - A recommended tech stack and architecture for the solution
        - Any technical constraints or considerations (e.g., performance, security, scalability)
        - Edge cases and potential challenges that may arise during development
        CRITICAL FORMATTING RULES:
        1. The 'requirements', 'constraints', and 'edge_cases' fields MUST be single strings in markdown format.
        2. You MUST output actual text content for every field in the output schema.
        3. DO NOT output the schema definition `{"type": "string"}` as a value. You must output the ACTUAL string.
        4. DO NOT use nested JSON objects, dictionaries, or lists within these fields.
        5. Use Markdown formatting (bullet points, bold text) INSIDE the string values to organize information.
        6. Double-check that you are not outputting a dictionary for requirements.

        ==================================================
        PROJECT DESCRIPTION
        ==================================================

        {project_description}
    expected output: |
        A valid JSON object matching the TechnicalSpecification schema.
    output schema: TechnicalSpecification

Task 2:
    name: Develop solution
    agent: Developer
    description: |
        Implement a solution based on the technical specification from the product manager.
        CRITICAL INSTRUCTIONS:
        1. **Separate Logic and Tests**: You MUST provide the implementation and the unit tests as separate files.
        2. **Naming Convention**: Name your test files starting with 'test_', for example: 'test_calculator.py'.
        3. **Comprehensive Coverage**: Develop unit tests that cover all edge cases defined in the specification (e.g., division by zero, empty inputs).
        4. **Runnable Code**: Ensure the test file imports the logic from the implementation file correctly.
    expected output: |
        A JSON object matching the DeveloperOutcome schema.
    output schema: DeveloperOutcome

Task 3:
    name: Provide code review
    agent: Code Reviewer
    description: |
        Perform an exhaustive code review of the solution provided by the developer.
        Your review MUST cover:
        1. **Specification Compliance**: Does the code implement EVERY requirement and handle every constraint defined in the Product Manager's Technical Specification?
        2. **Stack Best Practices**: Is the code written according to the highest standards of the selected stack?
        3. **Robustness**: Are edge cases (like division by zero or invalid inputs) handled as per the spec?
        4. **Test Quality**: Are the unit tests sufficient to cover the logic?
        CRITICAL RULES FOR DELEGATION:
        1. YOU are the reviewer. DO NOT delegate the task of "reviewing" the code to anyone else. You must read and analyze the code yourself.
        2. If and ONLY IF you find issues during your internal review, use the 'delegate_work_to_coworker' tool to assign a FIXING task to the developer.
        3. BATCH YOUR FEEDBACK. Do not make multiple tool calls. If there are multiple issues, send ONE single delegation task containing a bulleted list of all necessary fixes.
        4. The 'task' argument you delegate MUST contain actionable instructions on how to fix the code, NOT a request to review the code.
        5. DO NOT wrap your tool arguments in a "properties" object. Provide them at the root level.
        MAX PASSES FALLBACK:
        If you are forced to provide a final answer before the code is fully fixed (because you ran out of time or iterations), your Final verdict MUST be: 'REJECTED - MAXIMUM PASSES REACHED'.
    expected output: |
        A detailed review report in PURE MARKDOWN format.
        CRITICAL FORMATTING RULE: DO NOT output JSON for this final answer.
        Include a 'Compliance Matrix' comparing the code to the technical specification.
        List any bugs or stylistic violations separately.
        Final verdict MUST be: 'APPROVED' (if successful) OR 'REJECTED - MAXIMUM PASSES REACHED' (if you could not get the developer to fix it).

Task 4:
    name: Create final report
    agent: Crew Manager
    description: |
        Compile all deliverables from the team members into a structured JSON report:
        - Technical specification from the Product Manager
        - Developed solution and unit tests from the Developer
        - Review feedback from the Reviewer
        - Summary of the project outcome and any lessons learned
        IMPORTANT:
        - Do NOT include raw control characters.
        - Escape all double quotes (\") found inside the text.
        - If the feedback is very long, summarize it into clear paragraphs.
    expected output: |
        A valid JSON object matching the FinalReport schema.
        Do not include any conversational text outside the JSON.
        Every string field in the output must be formatted as a markdown document.
    output schema: FinalReport
