Task 1:
    name: Write detailed requirements and specifications
    agent: Product Manager
    description: |
        Based on the project description below, write detailed technical specification for the project.
        The specification should include:
        - A document title and a clear description of the project
        - The key features and functionalities required
        - A recommended tech stack and architecture for the solution
        - Any technical constraints or considerations (e.g., performance, security, scalability)
        - Edge cases and potential challenges that may arise during development

        ==================================================
        PROJECT DESCRIPTION
        ==================================================

        {project_description}
    expected output: |
        A valid JSON object matching the TechnicalSpecification schema.
        CRITICAL FORMATTING RULES:
        1. The 'requirements', 'constraints', and 'edge_cases' fields MUST be single strings.
        2. Do NOT use nested JSON objects, dictionaries, or lists within these fields.
        3. Use Markdown formatting (bullet points, bold text) INSIDE the string values to organize information.
        4. Example: "requirements": "- Feature A\n- Feature B\n- Feature C"
        5. Double-check that you are not outputting a dictionary for requirements.
    output pydantic: TechnicalSpecification

Task 2:
    name: Develop solution
    agent: Developer
    description: |
        Implement a solution based on the technical specification from the product manager.
    expected output: |
        A code block containing the developed solution, including unit tests.
        The code should be well-documented and follow best practices for maintainability and readability.

Task 3:
    name: Provide code review
    agent: Code Reviewer
    description: |
        Perform an exhaustive code review of the solution provided by the developer.
        Your review MUST cover:
        1. **Specification Compliance**: Does the code implement EVERY requirement and handle every constraint defined in the Product Manager's Technical Specification?
        2. **Stack Best Practices**: Is the code written according to the highest standards of the selected stack?
        3. **Robustness**: Are edge cases (like division by zero or invalid inputs) handled as per the spec?
        4. **Test Quality**: Are the unit tests sufficient to cover the logic?
        Provide a clear 'PASSED' or 'NEEDS CHANGES' status for each requirement.
    expected output: |
        A detailed review report in markdown format.
        Include a 'Compliance Matrix' comparing the code to the technical specification.
        List any bugs or stylistic violations separately.
        Final verdict: 'APPROVED' or 'REJECTED'.

Task 4:
    name: Create final report
    agent: Crew Manager
    description: |
        Compile all deliverables from the team members into a structured JSON report:
        - Technical specification from the Product Manager
        - Developed solution and unit tests from the Developer
        - Review report from the Reviewer
        - Summary of the project outcome and any lessons learned
    expected output: |
        A valid JSON object matching the FinalReport schema.
        Do not include any conversational text outside the JSON.
        Every string field in the output must be formatted as a markdown document.
    output pydantic: FinalReport
